server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb_topic_trainer
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: http://127.0.0.1:1234
      api-key: not-required
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/